[package]
name = "MyVMSTAT"
version = "1.2.12"
edition = "2021"
authors = ["AI Studio Developer"]
description = "A dstat-like colorized vmstat simulation written in Rust with Timestamps"
license = "MIT"

[dependencies]
sysinfo = "0.39"
chrono = "0.4"
# 2026-07-03: 共有ライブラリの参照追加
common_lib = { path = "../common_lib", features = ["windows_desktop"] }



[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = true

