name: CI Build

on:
  push:
    branches: [ master, main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master, main ]
    paths-ignore:
      - '**.md'

permissions:
  contents: write

jobs:
  check-test:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: MyVMSTAT

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          path: MyVMSTAT
          token: ${{ secrets.PAT || github.token }}

      - name: Checkout common_lib
        uses: actions/checkout@v7
        with:
          repository: tkshnkgwr/common_lib
          path: common_lib
          token: ${{ secrets.PAT || github.token }}

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Rust Cache
        uses: swatinem/rust-cache@v2

      - name: Cargo Check
        run: cargo check

      - name: Cargo Clippy
        run: cargo clippy -- -D warnings

      - name: Cargo Test
        run: cargo test
