name: CI Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  check-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Rust Cache
        uses: swatinem/rust-cache@v2

      - name: Cargo Check
        run: cargo check

      - name: Cargo Clippy
        run: cargo clippy -- -D warnings

      - name: Cargo Test
        run: cargo test
